
CMAKE_BUILD_TYPE=Release

BUILD_DIR=build-macos-m1-$CMAKE_BUILD_TYPE
mkdir -p $BUILD_DIR
cd $BUILD_DIR

cmake -G "Xcode" \
    -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
    -DCMAKE_CONFIGURATION_TYPES=$CMAKE_BUILD_TYPE \
    -DCMAKE_OSX_ARCHITECTURES="arm64" \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
    -DCMAKE_C_STANDARD=17 \
    -DCMAKE_CXX_STANDARD=17 \
    ..